#ifndef _M470_VISITOR_H
#define _M470_VISITOR_H

#include <OctaveVisitor.h>

namespace Llir
{

  class M470AddneInstruction;
  class M470AddneiInstruction;
  class M470AddwhInstruction;
  class M470AddwlInstruction;
  class M470AddwwInstruction;
  class M470AddlInstruction;
  class M470SubwhInstruction;
  class M470SubwlInstruction;
  class M470SubwwInstruction;
  class M470SublInstruction;
  class M470AddwhiInstruction;
  class M470AddwliInstruction;
  class M470AddwwiInstruction;
  class M470AddliInstruction;
  class M470SubwhiInstruction;
  class M470SubwliInstruction;
  class M470SubwwiInstruction;
  class M470SubliInstruction;
  class M470FfsInstruction;
  class M470FlsInstruction;
  class M470ParInstruction;
  class M470AddInstruction;
  class M470Add4xInstruction;
  class M470AddcInstruction;
  class M470AndInstruction;
  class M470MaxInstruction;
  class M470MinInstruction;
  class M470OrInstruction;
  class M470SubInstruction;
  class M470SubbInstruction;
  class M470XorInstruction;
  class M470AddiInstruction;
  class M470AddciInstruction;
  class M470SubiInstruction;
  class M470SubbiInstruction;
  class M470RandInstruction;
  class M470RotlInstruction;
  class M470RotrInstruction;
  class M470ClrbInstruction;
  class M470SetbInstruction;
  class M470ShftInstruction;
  class M470ShftaInstruction;
  class M470ShlInstruction;
  class M470ShrInstruction;
  class M470ShraInstruction;
  class M470RandiInstruction;
  class M470RotliInstruction;
  class M470RotriInstruction;
  class M470SetbiInstruction;
  class M470ClrbiInstruction;
  class M470ShliInstruction;
  class M470ShriInstruction;
  class M470ShraiInstruction;
  class M470MaxiInstruction;
  class M470MiniInstruction;
  class M470AndiInstruction;
  class M470OriInstruction;
  class M470XoriInstruction;
  class M470MulInstruction;
  class M470MulhInstruction;
  class M470DivInstruction;
  class M470MuliInstruction;
  class M470MulhiInstruction;
  class M470DiviInstruction;
  class M470AddneInstruction;
  class M470AddneiInstruction;
  class M470ByteswInstruction;
  class M470BcdrInstruction;
  class M470BcrInstruction;
  class M470BcdiInstruction;
  class M470BciInstruction;
  class M470BnzrInstruction;
  class M470BzrInstruction;
  class M470BnziInstruction;
  class M470BziInstruction;
  class M470TsetbInstruction;
  class M470TclrbInstruction;
  class M470RnmiInstruction;
  class M470RintInstruction;
  class M470BrsInstruction;
  class M470BrslInstruction;
  class M470BrspreInstruction;
  class M470CmpInstruction;
  class M470CmpiInstruction;
  class M470CmprInstruction;
  class M470CmpriInstruction;
  class M470BiInstruction;
  class M470BrInstruction;
  class M470DepbInstruction;
  class M470DepbiInstruction;
  class M470ExtbInstruction;
  class M470CmovInstruction;
  class M470CmoviInstruction;
  class M470DmapInstruction;
  class M470DmasrInstruction;
  class M470Dmau0Instruction;
  class M470Dmau1Instruction;
  class M470LihInstruction;
  class M470LilInstruction;
  class M470LwihInstruction;
  class M470LwilInstruction;
  class M470LaihInstruction;
  class M470LailInstruction;
  class M470NopInstruction;
  class M470Hec5Instruction;
  class M470MvInstruction;
  class M470MvhrInstruction;
  class M470MvrhInstruction;
  class M470UnlinkInstruction;
  class M470LinkInstruction;
  class M470LinksInstruction;

  class M470LmmInstruction;
  class M470LmmsInstruction;
  class M470LspInstruction;

  class M470SmmInstruction;
  class M470SmmsInstruction;
  class M470SspInstruction;

  class M470PutInstruction;
  class M470GetInstruction;
  class M470PolInstruction;
  class M470PutcInstruction;
  class M470GetcInstruction;
  class M470PolcInstruction;


  class M470Visitor
    {

    public:

      virtual void visit(const M470AddwhInstruction &) = 0;
      virtual void visit(const M470AddwlInstruction &) = 0;
      virtual void visit(const M470AddwwInstruction &) = 0;
      virtual void visit(const M470AddlInstruction &) = 0;
      virtual void visit(const M470SubwhInstruction &) = 0;
      virtual void visit(const M470SubwlInstruction &) = 0;
      virtual void visit(const M470SubwwInstruction &) = 0;
      virtual void visit(const M470SublInstruction &) = 0;
      virtual void visit(const M470AddwhiInstruction &) = 0;
      virtual void visit(const M470AddwliInstruction &) = 0;
      virtual void visit(const M470AddwwiInstruction &) = 0;
      virtual void visit(const M470AddliInstruction &) = 0;
      virtual void visit(const M470SubwhiInstruction &) = 0;
      virtual void visit(const M470SubwliInstruction &) = 0;
      virtual void visit(const M470SubwwiInstruction &) = 0;
      virtual void visit(const M470SubliInstruction &) = 0;
      virtual void visit(const M470FfsInstruction &) = 0;
      virtual void visit(const M470FlsInstruction &) = 0;
      virtual void visit(const M470ParInstruction &) = 0;
      virtual void visit(const M470AddInstruction &) = 0;
      virtual void visit(const M470Add4xInstruction &) = 0;
      virtual void visit(const M470AddcInstruction &) = 0;
      virtual void visit(const M470AndInstruction &) = 0;
      virtual void visit(const M470MaxInstruction &) = 0;
      virtual void visit(const M470MinInstruction &) = 0;
      virtual void visit(const M470OrInstruction &) = 0;
      virtual void visit(const M470SubInstruction &) = 0;
      virtual void visit(const M470SubbInstruction &) = 0;
      virtual void visit(const M470XorInstruction &) = 0;
      virtual void visit(const M470AddiInstruction &) = 0;
      virtual void visit(const M470AddciInstruction &) = 0;
      virtual void visit(const M470SubiInstruction &) = 0;
      virtual void visit(const M470SubbiInstruction &) = 0;  
      virtual void visit(const M470RandInstruction &) = 0;
      virtual void visit(const M470RotlInstruction &) = 0;
      virtual void visit(const M470RotrInstruction &) = 0;
      virtual void visit(const M470ClrbInstruction &) = 0;
      virtual void visit(const M470SetbInstruction &) = 0;
      virtual void visit(const M470ShftInstruction &) = 0;
      virtual void visit(const M470ShftaInstruction &) = 0;
      virtual void visit(const M470ShlInstruction &) = 0;
      virtual void visit(const M470ShrInstruction &) = 0;
      virtual void visit(const M470ShraInstruction &) = 0;
      virtual void visit(const M470RandiInstruction &) = 0;
      virtual void visit(const M470RotliInstruction &) = 0;
      virtual void visit(const M470RotriInstruction &) = 0;
      virtual void visit(const M470SetbiInstruction &) = 0;
      virtual void visit(const M470ClrbiInstruction &) = 0;
      virtual void visit(const M470ShliInstruction &) = 0;
      virtual void visit(const M470ShriInstruction &) = 0;
      virtual void visit(const M470ShraiInstruction &) = 0;
      virtual void visit(const M470MaxiInstruction &) = 0;
      virtual void visit(const M470MiniInstruction &) = 0;
      virtual void visit(const M470AndiInstruction &) = 0;
      virtual void visit(const M470OriInstruction &) = 0;
      virtual void visit(const M470XoriInstruction &) = 0;
      virtual void visit(const M470MulInstruction &) = 0;
      virtual void visit(const M470MulhInstruction &) = 0;
      virtual void visit(const M470DivInstruction &) = 0;
      virtual void visit(const M470MuliInstruction &) = 0;
      virtual void visit(const M470MulhiInstruction &) = 0;
      virtual void visit(const M470DiviInstruction &) = 0;
      virtual void visit(const M470AddneInstruction &) = 0;
      virtual void visit(const M470AddneiInstruction &) = 0;
      virtual void visit(const M470ByteswInstruction &) = 0;
      virtual void visit(const M470BcdrInstruction &) = 0;
      virtual void visit(const M470BcrInstruction &) = 0;
      virtual void visit(const M470BcdiInstruction &) = 0;
      virtual void visit(const M470BciInstruction &) = 0;
      virtual void visit(const M470BnzrInstruction &) = 0;
      virtual void visit(const M470BzrInstruction &) = 0;
      virtual void visit(const M470BnziInstruction &) = 0;
      virtual void visit(const M470BziInstruction &) = 0;
      virtual void visit(const M470TsetbInstruction &) = 0;
      virtual void visit(const M470TclrbInstruction &) = 0;
      virtual void visit(const M470RnmiInstruction &) = 0;
      virtual void visit(const M470RintInstruction &) = 0;
      virtual void visit(const M470BrsInstruction &) = 0;
      virtual void visit(const M470BrslInstruction &) = 0;
      virtual void visit(const M470BrspreInstruction &) = 0;
      virtual void visit(const M470CmpInstruction &) = 0;
      virtual void visit(const M470CmpiInstruction &) = 0;
      virtual void visit(const M470CmprInstruction &) = 0;
      virtual void visit(const M470CmpriInstruction &) = 0;
      virtual void visit(const M470BiInstruction &) = 0;
      virtual void visit(const M470BrInstruction &) = 0;
      virtual void visit(const M470DepbInstruction &) = 0;
      virtual void visit(const M470DepbiInstruction &) = 0;
      virtual void visit(const M470ExtbInstruction &) = 0;
      virtual void visit(const M470CmovInstruction &) = 0;
      virtual void visit(const M470CmoviInstruction &) = 0;
      virtual void visit(const M470DmapInstruction &) = 0;
      virtual void visit(const M470DmasrInstruction &) = 0;
      virtual void visit(const M470Dmau0Instruction &) = 0;
      virtual void visit(const M470Dmau1Instruction &) = 0;
      virtual void visit(const M470LihInstruction &) = 0;
      virtual void visit(const M470LilInstruction &) = 0;
      virtual void visit(const M470LwihInstruction &) = 0;
      virtual void visit(const M470LwilInstruction &) = 0;
      virtual void visit(const M470LaihInstruction &) = 0;
      virtual void visit(const M470LailInstruction &) = 0;
      virtual void visit(const M470NopInstruction &) = 0;
      virtual void visit(const M470Hec5Instruction &) = 0;
      virtual void visit(const M470MvInstruction &) = 0;
      virtual void visit(const M470MvhrInstruction &) = 0;
      virtual void visit(const M470MvrhInstruction &) = 0;
      virtual void visit(const M470UnlinkInstruction &) = 0;
      virtual void visit(const M470LinkInstruction &) = 0;
      virtual void visit(const M470LinksInstruction &) = 0;

      virtual void visit(const M470LmmInstruction &) = 0;
      virtual void visit(const M470LmmsInstruction &) = 0;
      virtual void visit(const M470LspInstruction &) = 0;

      virtual void visit(const M470SmmInstruction &) = 0;
      virtual void visit(const M470SmmsInstruction &) = 0;
      virtual void visit(const M470SspInstruction &) = 0;

      virtual void visit(const M470PutInstruction &) = 0;
      virtual void visit(const M470GetInstruction &) = 0;
      virtual void visit(const M470PolInstruction &) = 0;
      virtual void visit(const M470PutcInstruction &) = 0;
      virtual void visit(const M470GetcInstruction &) = 0;
      virtual void visit(const M470PolcInstruction &) = 0;
      
    };
  
}
#endif
