#!/usr/bin/env python
# -*- mode: python;-*-
#
# This is a simple filter that handles %if / %endif for Yacc files.
# The syntax is simple,
#
#   %if chipname
#     <body text will be ignored if chipname
#      does not match command-line argument>
#   %endif


import string
import sys

def usage():
    print "Usage: %s chipname input.y" % sys.argv[0]
    sys.exit(0)

def main():
    if len(sys.argv) != 3:
        usage()
    output = 1
    chip = sys.argv[1]
    f = open(sys.argv[2])
    for line in f.readlines():
        tokens = string.split(line)
        if len(tokens) and tokens[0] == "%if":
            if tokens[1] == chip:
                output = 1
            else:
                output = 0
            print ""
        elif len(tokens) and tokens[0] == "%endif":
            output = 1
            print ""
        else:
            if output:
                print line,
            else:
                print ""

main()
